# Generated by Django 6.0.3 on 2026-04-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='photo_about',
            field=models.ImageField(blank=True, null=True, upload_to='profil/'),
        ),
    ]
