# Generated by Django 6.0.7 on 2026-07-31 08:49

from django.db import migrations
from django.utils.text import slugify


def backfill_slugs(apps, schema_editor):
    Blog = apps.get_model('services', 'Blog')
    seen = set(Blog.objects.exclude(slug='').values_list('slug', flat=True))
    for blog in Blog.objects.filter(slug=''):
        base_slug = slugify(blog.titre) or f"post-{blog.pk}"
        slug = base_slug
        suffix = 2
        while slug in seen:
            slug = f"{base_slug}-{suffix}"
            suffix += 1
        seen.add(slug)
        blog.slug = slug
        blog.save(update_fields=['slug'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_blog_slug'),
    ]

    operations = [
        migrations.RunPython(backfill_slugs, noop),
    ]
