# Generated by Django 6.0.7 on 2026-07-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_backfill_blog_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='projets_contribues',
            field=models.IntegerField(default=25, help_text="Client/freelance/academic projects contributed to (not open source) — shown on the portfolio's projects section."),
        ),
    ]
