version: '3.8'

services:
  db:
    image: postgres:14
    command: postgres -p 5437
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5437:5437"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8100
    volumes:
      - .:/app
    ports:
      - "8100:8100"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
